name: Verify Dependabot Version Update (JavaScript)

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for JavaScript projects
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Ensure Node.js 18.x is used

      - name: Verify Node.js version
        run: node -v  # Check if the correct Node.js version is being used

      # Restore, Build, and Test all JavaScript projects
      - name: Install and Test JavaScript Projects
        run: |
          for dir in angular-spa msal-client-credentials-flow protect-api protect-function-app protected-api-access-protected-api react-spa vanillajs-spa; do
            echo "Processing directory: $dir"
            cd $dir
            npm install
            npm run test || npm test  # Some projects might use different commands
            cd ..
          done

  # dependabot-auto-merge:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Auto-merge Dependabot PR
  #       if: github.event.pull_request.user.login == 'dependabot[bot]'  # Only run on Dependabot PRs
  #       run: |
  #         gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
